### ISSUE TITLE
check ecto 2.0 compatibility 

### ISSUE THREAD

**Issue by williamgueiros** [williamgueiros/Brcpfcnpj#18]
Now you have new package 0.2.0
https://hex.pm/packages/brcpfcnpj

@esdras please, check your implementation is correct with the documentation ?

**Comment by williamgueiros** [comment]
and close this issues

**Comment by williamgueiros** [comment]
@esdras ping

**Comment by esdras** [comment]
Sorry, I don't see a "Close" button, not sure why. Can you close on your side?
