### ISSUE TITLE
mantenedor

### ISSUE THREAD

**Issue by williamgueiros** [williamgueiros/Brcpfcnpj#20]
@ulissesalmeida @VitorTrin @mvibraim

Pessoal, acho que a lib pode ser mantida por mais pessoas.
Acho que esta muito centralizada em mim.

Gostaria de saber se alguém esta afim ??

**Comment by VitorTrin** [comment]
Eu topo

**Comment by williamgueiros** [comment]
irei ver como lhe colocar no hex.pm, mas já lhe coloquei no github

**Comment by williamgueiros** [comment]
por acaso vc sabe como colocar mais de 1 no hex.pm ???

**Comment by ulissesalmeida** [comment]
pela linha de comando

```
mix hex.owner add PACKAGE EMAIL_OR_USERNAME
```

https://hexdocs.pm/hex/Mix.Tasks.Hex.Owner.html

**Comment by williamgueiros** [comment]
@VitorTrin me passa o seu usuario no hex.pm

**Comment by VitorTrin** [comment]
vitortrin

**Comment by williamgueiros** [comment]
Done.
