### ISSUE TITLE
Não considerar certos casos como CNPJ válido

### ISSUE THREAD

**Issue by leandro** [williamgueiros/Brcpfcnpj#29]
Eu percebi que há alguns casos em que certas entradas de 14 dígitos não deveriam estar sendo consideradas como CNPJ válidos.

A questão é: há casos onde me é informado entradas variadas de 14 dígitos, onde precisamos verificar se essa entrada é um CNPJ válido ou um CPF válido (removendo os 3 primeiros dígitos). E por conta disso me deparei com um caso onde tanto os 14 dígitos configuram como um CNPJ válido, quanto os últimos 11 dígitos configuram como um CPF válido (quando a realidade é que essa entrada é apenas um CPF válido).

Percebi que a solução se dá fazendo certas verificações para o caso de CNPJs e, para isso, segue uma citação que extraí desse [link aqui](https://www.guj.com.br/t/identificacao-cpf-ou-cnpj-com-mesma-quantidade-de-caracteres/324740/7):
> Não será considerado válido CNPJ com número de ORDEM igual a 0000
Não será considerado válido CNPJ com número de ORDEM maior do que 0300 e com as três primeiras posições do número BÁSICO com 000 (zeros). Esta crítica não será feita, quando o no básico do CNPJ for igual a 00.000.000

Acredito que atualmente a lib não está levando em consideração essas regras acima na hora de validar o CNPJ. O que acha de incluirmos isso no algoritmo de validação de CNPJ? Se precisarem de um suposto CNPJ (que na verdade é um CPF) que caia nesse caso, me peçam no privado (meu e-mail: leandroico@gmail.com), para que não se exponha publicamente CPF de terceiros por aqui.

**Comment by VitorTrin** [comment]
Oi @leandro , abri o pr que valida esses casos levantados nesse link e mais alguns, você saberia de algum link para uma documentação oficial? Gostaria de colocar o link comentado no código

**Comment by leandro** [comment]
Olá, @VitorTrin. O lugar mais "oficial" que achei que fala respeito disso é nesse link aqui: http://www.receita.fazenda.gov.br/publico/Legislacao/atos/AtosConjuntos/AnexoIADEConjuntoCoratCotec0012002.doc

**Comment by VitorTrin** [comment]
Eu também achei esse documento, mas ele está solto e não parece que o objetivo dele é definir as validações de cnpj e cpf, só está reproduzindo
