### ISSUE TITLE
Add support for Ecto changesets

### ISSUE THREAD

**Issue by tiagoengel** [williamgueiros/Brcpfcnpj#3]
I was thinking on adding some methods to add support for the Ecto changeset api.
Would look something like this:
```elixir
model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_cnpj(:cnpj, message: "Cnpj inválido')
```

What do you think?

**Comment by williamgueiros** [comment]
clean and beautiful.
go ahead :+1:

**Comment by williamgueiros** [comment]
more one point, remember create test to this feature .

**Comment by williamgueiros** [comment]
@tiagoengel 
What do you thing, change validate_cnpj and validate_cpf to validate_cpfcnpj and using atom to select the correct validation ?

**Comment by tiagoengel** [comment]
Maybe internally we could do that, but I prefer the API with the two functions, 'cause a function call like this would be a little bit confusing.
```elixir
validate_cpfcnpf(:cnpj, :cnpj)
```

**Comment by williamgueiros** [comment]
ok no problem. i close de issue.

**Comment by williamgueiros** [comment]
:+1: 

2 functions is good, i don't understend why using atom 
```
validate_cnpj(:cnpj, message: "Cnpj inválido')
validate_cpf(:cpf, message: "Cpf inválido')

```
instead

```
validate_cnpj(message: "Cnpj inválido')
validate_cpf(message: "Cpf inválido')
```

is a Ecto limitation ?

**Comment by tiagoengel** [comment]
:cnpj/:cpf in this case are field names. For instance, if I have a model definition like this:
```elixir
defmodule Company do

  schema "companies" do
    field :name, :string
    field :numero_cnpj, :string
  end
end
```
I would have to call the function this way: 
```elixir
validate_cnpj(:numero_cnpj, message: "Cnpj inválido')
```

**Comment by williamgueiros** [comment]
:heart: :green_heart: :blue_heart:
