### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jdanielnd** [williamgueiros/Brcpfcnpj#35]
Hi everyone :)

First of all, thanks for developing and maintaining this library. I notice the repository doesn't present any license. Is it licensed to be used on other softwares? If it is, is there any willingness to setup a license for this repository?

Thanks!

**Comment by VitorTrin** [comment]
@williamgueiros Essa aqui tem de ser você

**Comment by williamgueiros** [comment]
@VitorTrin estou em duvida entre a Apache 2 e a MIT, gostaria a mais permissiva possível. Mas não quero a loucura da GNU.
vc tem alguma sugestão ???
