### ISSUE TITLE
Improve random number generation

### ISSUE THREAD

**Issue by guilhermefloriani** [williamgueiros/Brcpfcnpj#5]
Today, the way used to create random numbers in CNPJ or CPF generation can cause a "bug" when you use that in multiple tests or sessions, generating the same sequence of CNPJ's or CPF's for all of them.

i.e.
Starts a iex session and generate a random CNPJ:
```iex(1)> Brcpfcnpj.cnpj_generate``` results in ```"21546853597400" ```
If you starts another iex session and use the same function, you'll get the same result (```"21546853597400"```).

To solve that problem, I suggest to change from ```random``` erlang module to ```rand``` module, which was released in Erlang 18 and improve these random number generation.

I did some tests using the ```rand``` module and this solves the problem, if you wan't I can do the changes.

**Comment by williamgueiros** [comment]
See that https://github.com/elixir-lang/elixir/issues/3212
Elixir 1.2 have a support the solution is the same you say, but if resolve using that solution the project doesn't work in elixir 1.0.

@diogobeda and @tiagoengel, do you like remove support elixir 1.0 ?

**Comment by williamgueiros** [comment]
To me :+1:  and update version to 0.1.0

**Comment by tiagoengel** [comment]
I don't see any problem on breaking the compatibility with erlang 17 and elixir < 1.2.

But if you don't want to break the compatibility, you can use the [seed](http://erlang.org/doc/man/random.html#seed-3) function, like so:

```elixir
defmodule Randomise do 
  @on_load :reseed_generator 

  def reseed_generator do 
    :random.seed(:erlang.now()) 
  end
end
```

In fact, I think it's also a good practice to do that even using the ```:rand``` module (it also have a seed function).

**Comment by guilhermefloriani** [comment]
For me it's ok still using the ```:random``` module to don't lose compatibility with elixir < 1.2, but doing that changes suggested by @tiagoengel.

**Comment by diogobeda** [comment]
Agreed with both of you. The least versions we lose compatibility the better.

**Comment by diogobeda** [comment]
Also, using reactions now just because I can. rs

**Comment by williamgueiros** [comment]
please see that in 12 mim  http://youtu.be/YlNrWxH56_E
OTP 19 putting the Radom in deprecated mode .

I believe is good opportunity to resolve this problem and prepares to next version

**Comment by diogobeda** [comment]
Oh, thanks @williamgueiros. I didn't know about that. Having that in mind, I also think it's better to use `rand`.

**Comment by williamgueiros** [comment]
@tiagoengel @guilhermefloriani what do you thing, after see this video?

**Comment by tiagoengel** [comment]
If it will be deprecated I think would be better to use the ``:rand`` module

**Comment by williamgueiros** [comment]
ups remove support to elixir < 1.2, fail comment
