### ISSUE TITLE
Changeset validation errors problem

### ISSUE THREAD

**Issue by mauricioszabo** [williamgueiros/Brcpfcnpj#7]
When adding validation errors on changeset functions, things are being added incorrectly: for example, this is how "default" errors in Ecto are being added:

```
errors: [name: {"can't be blank", [validation: :required]}
```

And this is how BrCNPJ are being added:

```
errors: [contract: "Document format invalid",
```

This means that FallbackController can't parse correctly these errors, and we're getting a run-time exception:

```
     ** (FunctionClauseError) no function clause matching in AppWeb.ErrorHelpers.translate_error/1

     The following arguments were given to AppWeb.ErrorHelpers.translate_error/1:
     
         # 1
         "Invalid Cnpj"
     
     Attempted function clauses (showing 1 out of 1):
     
         def translate_error({msg, opts})
```

**Comment by williamgueiros** [comment]
@tiagoengel do you think, is possible to help us, with that ?

**Comment by mauricioszabo** [comment]
Yep, I can. I'll submit a PR as soon as I can.

**Comment by williamgueiros** [comment]
Yes , tanks for you help

**Comment by williamgueiros** [comment]
And go ahead

**Comment by tiagoengel** [comment]
if I'm not mistaken this new error format is for ecto 2.0 onwards so it may be a good idea to update the lib's main version and indicate somewhere that the latest version is only compatible with the newest ecto version. Otherwise it may break old code using this lib

**Comment by williamgueiros** [comment]
create major release 0.1.0 to 0.2.0
and add readme Information.

**Comment by williamgueiros** [comment]
close that, in favor of #17
