### ISSUE TITLE
cpf_valid error - nil

### ISSUE THREAD

**Issue by eriknakata** [williamgueiros/Brcpfcnpj#9]
Guys,

I had an issue with the function cnpj_valid? when the input is "nil".

Example:

`Brcpfcnpj.cpf_valid?(%Cpf{number: nil})`

Result:

`** (FunctionClauseError) no function clause matching in Regex.replace/4`

I think would be great is the function returns "false" with nil cases.

Can I send a pull request with the fix?

**Comment by williamgueiros** [comment]
hello 

tomorrow, i will creta new release to you

**Comment by williamgueiros** [comment]
sorry delay

**Comment by williamgueiros** [comment]
fix in version 0.1.1
